const languageMap = {
    AR: "Arabic",
    BG: "Bulgarian",
    BN: "Bengali",
    CA: "Catalan",
    CS: "Czech",
    DA: "Danish",
    DE: "German",
    EL: "Greek",
    EN: "English",
    ES: "Spanish",
    ET: "Estonian",
    FA: "Persian",
    FI: "Finnish",
    FR: "French",
    HE: "Hebrew",
    HI: "Hindi",
    HR: "Croatian",
    HU: "Hungarian",
    ID: "Indonesian",
    IS: "Icelandic",
    IT: "Italian",
    JA: "Japanese",
    KA: "Georgian",
    KN: "Kannada",
    KO: "Korean",
    LT: "Lithuanian",
    LV: "Latvian",
    MK: "Macedonian",
    ML: "Malayalam",
    MR: "Marathi",
    MS: "Malay",
    NB: "Norwegian Bokmål",
    NL: "Dutch",
    NO: "Norwegian",
    PA: "Punjabi",
    PL: "Polish",
    PT: "Portuguese",
    RO: "Romanian",
    RU: "Russian",
    SK: "Slovak",
    SL: "Slovenian",
    SQ: "Albanian",
    SR: "Serbian",
    SV: "Swedish",
    TA: "Tamil",
    TE: "Telugu",
    TH: "Thai",
    TR: "Turkish",
    UK: "Ukrainian",
    UR: "Urdu",
    VI: "Vietnamese",
    ZH: "Chinese",
  }
  
  export const getCountryName = (countryCode) => {
    return languageMap[countryCode.toUpperCase()] || countryCode
  }
  